//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace djiDaiLy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DiemKyThuat
    {
        public int id { get; set; }
        public int Point { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public string userID { get; set; }
        public int actid { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
