//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace djiDaiLy.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ThienNgaDatabaseEntities : DbContext
    {
        public ThienNgaDatabaseEntities()
            : base("name=ThienNgaDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<ActivityType> ActivityTypes { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<CustomerType> CustomerTypes { get; set; }
        public virtual DbSet<DiemKyThuat> DiemKyThuats { get; set; }
        public virtual DbSet<employee> employees { get; set; }
        public virtual DbSet<HangBaoHanh> HangBaoHanhs { get; set; }
        public virtual DbSet<inventory> inventories { get; set; }
        public virtual DbSet<item> items { get; set; }
        public virtual DbSet<log> logs { get; set; }
        public virtual DbSet<NhanVien> NhanViens { get; set; }
        public virtual DbSet<order> orders { get; set; }
        public virtual DbSet<orderDetail> orderDetails { get; set; }
        public virtual DbSet<RequestMuon> RequestMuons { get; set; }
        public virtual DbSet<RequestStatu> RequestStatus { get; set; }
        public virtual DbSet<role> roles { get; set; }
        public virtual DbSet<tb_cate> tb_cate { get; set; }
        public virtual DbSet<tb_customer> tb_customer { get; set; }
        public virtual DbSet<tb_inventory_name> tb_inventory_name { get; set; }
        public virtual DbSet<tb_product_detail> tb_product_detail { get; set; }
        public virtual DbSet<tb_warranty> tb_warranty { get; set; }
        public virtual DbSet<tb_warranty_activities> tb_warranty_activities { get; set; }
        public virtual DbSet<tb_warrnaty_status> tb_warrnaty_status { get; set; }
        public virtual DbSet<ThongBaoMoi> ThongBaoMois { get; set; }
        public virtual DbSet<warrantyActivityFee> warrantyActivityFees { get; set; }
        public virtual DbSet<warrantyActivityFixingFee> warrantyActivityFixingFees { get; set; }
    }
}
