//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace djiDaiLy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class log
    {
        public int id { get; set; }
        public int warrantyActivitiesID { get; set; }
        public string action { get; set; }
        public System.DateTime date { get; set; }
        public string account { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual tb_warranty_activities tb_warranty_activities { get; set; }
    }
}
