//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace djiDaiLy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RequestMuon
    {
        public int id { get; set; }
        public Nullable<int> productID { get; set; }
        public int quantity { get; set; }
        public int status { get; set; }
        public string creator { get; set; }
        public System.DateTime createdDate { get; set; }
        public Nullable<System.DateTime> recieveDate { get; set; }
        public Nullable<System.DateTime> returnDate { get; set; }
        public string TemporaryName { get; set; }
        public string Description { get; set; }
        public Nullable<int> warrantyID { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
        public virtual tb_product_detail tb_product_detail { get; set; }
        public virtual tb_warranty_activities tb_warranty_activities { get; set; }
    }
}
