//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace djiDaiLy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThongBaoMoi
    {
        public int id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Reciever { get; set; }
        public bool Confirmed { get; set; }
        public string hreflink { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
